### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by riley-stroud-ck** [thebigredgeek/apollo-errors#10]
I'm hoping I'll have time to work on this soon, but what are your thoughts on adding Typescript support versus a complete rewrite in Typescript?

**Comment by thebigredgeek** [comment]
I was actually hoping to completely rewrite in TS.  But we can add support in the mean time if that would be better for most people

**Comment by thebigredgeek** [comment]
@riley-stroud-ck would you like to help with either of those options?

**Comment by riley-stroud-ck** [comment]
@thebigredgeek I started on a complete rewrite in Typescript over the weekend. I'm hoping to push it tomorrow morning.

**Comment by thebigredgeek** [comment]
Woot!  Thanks @riley-stroud-ck

**Comment by thebigredgeek** [comment]
Hey @riley-stroud-ck , did you ever get around to finishing that PR?

**Comment by riley-stroud-ck** [comment]
Nope, I got stuck with some dependency types not working and haven't picked it up again for a while

**Comment by thebigredgeek** [comment]
:(

**Comment by rasdaniil** [comment]
https://github.com/thebigredgeek/apollo-errors/pull/22
