### ISSUE TITLE
Handling errors on the client (react-apollo)

### ISSUE THREAD

**Issue by SachaG** [thebigredgeek/apollo-errors#12]
I've managed to set up this awesome package without trouble (I get the expected JSON output in my requests) but I'm not sure what to do from there. 

My issue is that when I throw an error inside a mutation handled by react-apollo's `graphql` HoC, the `error` object returned by the promise doesn't contain the custom error properties defined on the server, only the `message`.

Am I doing something wrong? How are you supposed to catch custom errors on the client?

**Comment by knowthen** [comment]
It looks like you grab the `graphQLErrors` property on the error.  

Here's an example: 

```
{
  "graphQLErrors": [
    {
      "message": "Unable to login",
      "name": "LoginError",
      "time_thrown": "2017-06-29T19:16:19.841Z",
      "data": {
        "someExtraInfo": "passed Along"
      }
    }
  ],
  "networkError": null,
  "message": "GraphQL error: Unable to login"
}
```

**Comment by SachaG** [comment]
That did the trick, thanks!

**Comment by slightlytyler** [comment]
Hmm it was accessible at `err.graphQLErrors[0].originalError` for me. Would be great to clarify this somewhere in the docs

**Comment by thebigredgeek** [comment]
Agreed.  The docs can be improved.  The problem, though, is that a lot of this depends on Apollo and not on this package, which is BE specific.
