### ISSUE TITLE
Pattern for when user logs out?

### ISSUE THREAD

**Issue by acomito** [thebigredgeek/apollo-errors#14]
I have setup my resolvers, one of which is:

```
export const UnauthorizedError = createError('UnauthorizedError', {
	message: 'You must login to do that'
});

```

- I have a login page, which checks to see if a user is logged in (looking in apollo store).

- If the user is logged in, the page will kick them into the "authenticated area" of the app.

- When a user is inside the app, they can click a logout button. This logout mutation returns a promise. In the .then(), I re-route the user to the login page. 

- If I were to re-route them to /login prior to the .then(), they would just get kicked back into the auth area (apollo store still thinks they're logged in).

My problem:

- The user clicks logout, mutation runs, server is aware the user is no longer logged in

- My .then() hasn't re-routed the user, so all of the queries are re-running and throwing "UnauthorizedError: You must login to do that" whenever somebody logs out.

Is my only option to update the store with optimistic UI, and kick them back to login page? Or is there a different pattern to use with my errors/resolvers on the server?

**Comment by thebigredgeek** [comment]
Hmm, yeah you shouldn't re-run queries that expect an authenticated state once you've logged out.  this seems like something you'll need to handle on the client
