### ISSUE TITLE
Global "show locations"

### ISSUE THREAD

**Issue by ygotthilf** [thebigredgeek/apollo-errors#15]
Hello,

Thank you for this great module. I want to use it but I need the following improvement.

I think `formatError` should take in argument `showLocations` in order to hide or show the locations and path of any error.
Actually, to my mind, the implementation where the error is created is not responsible for how the error must be formatted/displayed : this is the role of `formatError` function.

If you agree I can open a PR.

What do you think ?

Best,

Yoann

**Comment by ch-andrewrhyne** [comment]
Yeah sure put in a PR!  This would be useful for debugging at dev time.

**Comment by thebigredgeek** [comment]
^ Me btw haha

**Comment by thebigredgeek** [comment]
I'm closing this for now since I haven't heard anything in a while
