### ISSUE TITLE
Rewrite in typescript

### ISSUE THREAD

**Issue by thebigredgeek** [thebigredgeek/apollo-errors#16]

**Comment by lakhansamani** [comment]
@thebigredgeek Is there any repo or branch where this work is started?

**Comment by thebigredgeek** [comment]
Not yet, nope!  But I am looking for help with it if you wanna get started?

**Comment by lakhansamani** [comment]
Sure, would love to do that

**Comment by thebigredgeek** [comment]
Awesome!  I look forward to your PR :D

**Comment by lakhansamani** [comment]
Hey @thebigredgeek I have tried making typescript version, you can check here https://github.com/lakhansamani/apollo-errors/tree/typescript

Please share your feedback on this on how we want to build and publish it

**Comment by thebigredgeek** [comment]
Looks good so far!  Are we able to get the existing tests passing?

Also, it might be a good idea to add types the `createError` config property etc.  Basically anything that is in interface between components and to the outside world.

**Comment by lakhansamani** [comment]
@thebigredgeek test cases are passing so far

Can you explain how you want to add types, that part was not clear

**Comment by thebigredgeek** [comment]
Right, so there is an interface for the `ApolloError` constructor as well as the `createError` function.  We should have a typed interface for these, and create an entry for [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) so that people can install the type definitions
