### ISSUE TITLE
Looking for additional core contributors

### ISSUE THREAD

**Issue by ch-andrewrhyne** [thebigredgeek/apollo-errors#17]
Post here if you want core contrib access.  Looking for 1 or 2 people to help

**Comment by meel-io** [comment]
Count me in

**Comment by savovs** [comment]
Heyo, I'm a noob but would love to contribute.

**Comment by thebigredgeek** [comment]
Bump.  Is anyone here interested?  I need halp!

**Comment by meel-io** [comment]
I'm in 👍

**Comment by ch-andrewrhyne** [comment]
@meel-io done!

**Comment by ayoubice** [comment]
We have started using this package as the main error handler. It has saved a lot of time and efforts for us. I will be more than happy to contribute to this project.

**Comment by theGlenn** [comment]
Count me in if you still need help 🙌
