### ISSUE TITLE
Print query that caused the error

### ISSUE THREAD

**Issue by wmertens** [thebigredgeek/apollo-errors#18]
It would be good to know what query caused the error and what the variables were… Maybe just in dev mode due to lots of data and possible password leaks…

**Comment by wmertens** [comment]
Err - I just realized that I am expecting logging from graphql-errors, not apollo-errors 🙄 . Sorry for the noise.

**Comment by thebigredgeek** [comment]
Haha.  Why so much love for `graphql-errors` rather than this lib? :p

**Comment by wmertens** [comment]
I was thinking I should look at the error stuff that you wrote so I found
that by accident and I thought you worked at Kadira :)

I thought hiding server errors was a good idea so I started using it… it's
really orthogonal to your library though…
