### ISSUE TITLE
Recomendation for better implamantation

### ISSUE THREAD

**Issue by GiladShoham** [thebigredgeek/apollo-errors#2]
Hi,

I Have just implemented a similar library.
And just now I found out that instead of all the serialize and deserialize with delimiter mechanism you use.
You can just get the custom error that way:

```js
formatError: function (error) {
  const customError = error.originalError;
  // Add path locations etc'
  return customError
}
```

see more in the graphql source [here](https://github.com/graphql/graphql-js/blob/44f315d1ff72ab32b794937fd11a7f8e792fd873/src/error/GraphQLError.js#L66-L69)

I did the same mistake, and I'm planning to change it since it much cleaner and correct.

**Comment by thebigredgeek** [comment]
Ah nice!  Care to make a PR?

**Comment by GiladShoham** [comment]
I can make it, but it will take some time since I'm going to be out of the country for some time.

**Comment by thebigredgeek** [comment]
Done!

**Comment by thebigredgeek** [comment]
https://github.com/thebigredgeek/apollo-errors/commit/e20f9abe35f38320176e040553555f21ea9ea3c3
