### ISSUE TITLE
Integration with apollo-server

### ISSUE THREAD

**Issue by druidsgarden** [thebigredgeek/apollo-errors#20]
Just wondering whether you'd tried to get the package working with `apollo-server` yet? We are using it within Serverless as a Lambda rather than using Express.

**Comment by thebigredgeek** [comment]
This should work with `apollo-server` out of the box.  It was designed to work with it

**Comment by druidsgarden** [comment]
Not with `apollo-server-lambda` it doesn't seem to. I don't know whether it's down to the version of NodeJS we are restricted to (6.10) or my lack of knowledge of NodeJS as I'm fairly new to it. 

I did get it all working eventually but I had to make the following changes: 

I had to change the imports to use const and define each module discretely

The Error definitions all needed to be in seperate JS files: 

```
'use strict';

const createError = require("apollo-errors").createError;

const UnknownError = createError('UnknownError',{
    message: 'An unknown error has occured'
});

module.exports = UnknownError;
```

In the apollo-handler

`const formatError = require('apollo-errors').formatError;`

`const graphQLOptions = {
            schema: jsSchema,
            context: {
                "resolvers": Resolvers   
            },
            formatError: formatError,
            debug: true
        };                                                      

        //console.log(jsSchema);
        server.graphqlLambda(graphQLOptions)(event, context, callbackFilter);`

I could then just throw the Error as needed. 

It's a great library btw.

**Comment by thebigredgeek** [comment]
Can you confirm whether or not this is still an issue with Lambda?

**Comment by n1ru4l** [comment]
I am using this package with apollo-server-lambda, it works fine and it is totally awesome! Thank you, I think we can close this issue ☺️
