### ISSUE TITLE
Handle GraphQLError

### ISSUE THREAD

**Issue by LuisUrrutia** [thebigredgeek/apollo-errors#21]
I'm working with apollo-server-express, and I've created a custom scalar:

```javascript
const regex = /^(([^<>()[\].,;:\s@"]+(\.[^<>()[\].,;:\s@"]+)*)|(".+"))@(([^<>()[\].,;:\s@"]+\.)+[^<>()[\].,;:\s@"]{2,})$/i;

export default {
  name: 'EmailString',
  description: 'E-Mail addresses compliant to RFC 822.',
  parseValue: (value) => {
    if (typeof value !== 'string') {
      throw new TypeError('Invalid Email input value (string expected)');
    }
    if (!regex.test(value)) {
      throw new TypeError('Invalid Email input value');
    }
    return value;
  },
  serialize: value => value,
  parseLiteral: (ast) => {
    if (ast.kind !== Kind.STRING) {
      throw new TypeError('Invalid Email input value (string expected)');
    }
    if (!regex.test(ast.value)) {
      throw new TypeError('Invalid Email input value');
    }
    return ast.value;
  },
};
```

But when it throws the error, formatError doesn't parse it 'cause it's an GraphQLError:

```javascript
if (!name || !isInstance(originalError)) return returnNull ? null : error;
```
`name` is evaluated to `GraphQLError` string, then the response it's like this:

```
{
  "errors": [
    {
      "message": "Variable \"$email\" got invalid value \"asd\".\nExpected type \"UEmail\", found \"asd\": Invalid Email input value",
      "locations": [
        {
          "line": 1,
          "column": 45
        }
      ]
    }
  ]
}
```

And not how I expected to be:

```
{
  "data": {
    "addEmail": null
  },
  "errors": [
    {
      "message": "Invalid Email input value",
      "name": "TypeError",
      "time_thrown": "2017-10-22T13:48:28.989Z",
      "data": {}
    }
  ]
}
```

**Comment by thebigredgeek** [comment]
Can you reproduce this with a test?  And what version of apollo-server-express are you using?

**Comment by guikubivan** [comment]
This also happens just with `graphql` and `express-graphql` (not apollo server).

**Comment by thebigredgeek** [comment]
Hmm looks like perhaps other server implementations are swallowing the error.  We actually had a way of handling this before but we removed it when Apollo Server fixed the error masking "regression".  I'll look into this over thanksgiving!  Thanks for the report

**Comment by thebigredgeek** [comment]
Can you confirm that this is still an issue?

**Comment by yhjor** [comment]
https://github.com/thebigredgeek/apollo-errors/issues/21#issuecomment-366804523
For me, yes.

The FE only recongizes `GraphQLError` instead of the custom one.

**Comment by thebigredgeek** [comment]
Hmm, what do you mean the FE?  This lib is only really concerned with the BE response, not how the FE processes it.

**Comment by thebigredgeek** [comment]
After re-reading this, I feel like I have a better handle on this.  Our lib doesn't currently "transform" external errors automatically into "ApolloError" instances.  However, I'd love to implement something like that!  Do you happen to have time to submit a PR to add that functionality?

**Comment by yhjor** [comment]
Not exactly FE, but the error instance input from `formatError` appears with `GraphQLError` instead of the defined one.

Let me take a look inside and if I have time to make a PR with it.

**Comment by thebigredgeek** [comment]
Right that might be because it's not an instance of an `ApolloError`, which unfortunately isn't the same thing :(

**Comment by lxcid** [comment]
I'm facing similar issue as well though. :(
