### ISSUE TITLE
Work with schema stitching.

### ISSUE THREAD

**Issue by j** [thebigredgeek/apollo-errors#23]
`apollo-errors` doesn't work when using `mergeSchemas`.

**Comment by babbarankit** [comment]
Same issue.

**Comment by thebigredgeek** [comment]
oh wow! I haven't actually had a use case that requires `mergeSchemas` yet.  Let me look into this over thanksgiving break!  Can someone post an example or test case?  That would be super useful

**Comment by makstr** [comment]
@j Perhaps this is outdated, but as of now I do not seem to be having any problems with mergeSchemas

**Comment by thebigredgeek** [comment]
Ok cool.  I'll close this.  Thanks!
