### ISSUE TITLE
Data values as array of object instead of object

### ISSUE THREAD

**Issue by rohmanhm** [thebigredgeek/apollo-errors#25]
If I put the data value as an object like your example
```js
import { FooError } from './errors';

const resolverThatThrowsError = (root, params, context) => {
  throw new FooError({
    data: {
      something: 'important'
    }
  });
}
```
That will throwing something like this.
```json
{
  "data": {},
  "errors": [
    {
      "message":"A foo error has occurred",
      "name":"FooError",
      "time_thrown":"2016-11-11T00:40:50.954Z",
      "data":{
        "something": "important"
      }
    }
  ]
}
```

But, if I put my data as an array of object.
```js
import { FooError } from './errors';

const resolverThatThrowsError = (root, params, context) => {
  throw new FooError({
    data: [{
		something: 'important'
	}, {
		something: 'very important'
	}]
  });
}
```
Why it's throwing the data as object, not an array of object?

```json
{
  "data": {},
  "errors": [
    {
      "message":"A foo error has occurred",
      "name":"FooError",
      "time_thrown":"2016-11-11T00:40:50.954Z",
      "data": {
		 "0": {
	        "something": "important"
	      },
		"1": {
	        "something": "very important"
	      }
      }
    }
  ]
}
```

I need my data to be an array of object, is that possible?

**Comment by thebigredgeek** [comment]
This is definitely a bug.  I'll look into it

**Comment by thebigredgeek** [comment]
Actually, after looking, this isn't actually a bug.  We dereference the data passed into the error constructor and merge the two objects together (the definition data and the instance data).  For that reason, we both values to either be of the same type (`Object`) or empty (`null`/`undefined`).

Could your use case be satisfied by inserting an array onto the `data` object as a property?  It should serialize correctly if you do this
