### ISSUE TITLE
es6-error v4.1.0 breaks formatError

### ISSUE THREAD

**Issue by gordonk** [thebigredgeek/apollo-errors#26]
Thanks for your library.  Its a great little helper.

in formatError function, with es6-error v4.0.6..
!name false
!isInstance(originalError) false

in formatError function, with es6-error v4.1.0..
!name false
!isInstance(originalError) true

Which prevents the serialization of the new merged message and just returns the original message without any data, processing of location/path options etc.

Fixing es6-error at 4.0.6 in project's package.json fixes this as a workaround.

**Comment by thebigredgeek** [comment]
Can you submit a PR?

**Comment by thebigredgeek** [comment]
`es6-error` isn't used in this lib.  Can you give more context to your issue?  Are you throwing an `es6-error` yourself?

**Comment by maxtechera** [comment]
`es6-error` was used in version 1.5.1. Try updating your `apollo-errors` version!

**Comment by gordonk** [comment]
Hopefully anyone stumped between 15/1 and 22/2 when 1.7 came out was helped :)
Thanks for the util @thebigredgeek.  Use it in all my projects.
