### ISSUE TITLE
GraphQL response is always null

### ISSUE THREAD

**Issue by dakshshah96** [thebigredgeek/apollo-errors#31]
I have a mutation to create an admin for my system:

```js
mutation {
  createAdmin(
    name:"Test"
    phoneNumber:"8758"
    password:"12345"
  ) {
    _id
    createdAt
    updatedAt
  }
}
```

The mutation definition is like this:

```js
const { UnknownError } = require('../../../helpers/errors')

const createAdmin = async (payload) => {
  try {
    const { error, value } = Joi.validate(payload, adminReqSchema)
    if (error) {
      throw new UnknownError({
        data: {
          reason: 'Schema validation error'
        }
      })
    }

    const admin = await new Admin({ name: value.name, phoneNumber: value.phoneNumber }).save()
    await new Auth({ userId: admin._id, role: 'admin', password: value.password }).save()

    return admin
  } catch (err) {
    console.log(err)
  }
}
```

I've defined my error here:

```js
const { createError } = require('apollo-errors')

const UnknownError = createError('UnknownError', {
  message: 'An unknown error has occured'
})

module.exports = { UnknownError }
```

The response is get is always:

```js
{
  "data": {
    "createAdmin": null
  }
}
```

**EDIT**: I've narrowed down this problem to the fact that I'm using `async/await` in my mutation functions and handling errors using `try/catch` blocks. I'd like to know the right way to use apollo-errors with `async/await` and `try/catch` blocks.

**Comment by luisgrases** [comment]
#32

**Comment by guico33** [comment]
Hi, how about rethrowing any caught `ApolloError`? That way it should work as intended and you can still manage the error handling of any other operation the way you want. 
```javascript
import { ApolloError } from 'apollo-errors'
/* ... */
} catch (err) {
  if (err instanceof ApolloError) throw(err) 
}
```

**Comment by thebigredgeek** [comment]
Yes, if you are already catching the error then you need to re-throw it if you want the error to continue propagating.  Otherwise, you've already handled the error and the Promise won't reject.
