### ISSUE TITLE
How to add formatError to subscriptions end-point

### ISSUE THREAD

**Issue by gijo-varghese** [thebigredgeek/apollo-errors#38]
My Apollo client uses subscription endpoint for both queries and mutations. How can I use it for subscription end-point?

**Comment by gijo-varghese** [comment]
https://github.com/apollographql/subscriptions-transport-ws/issues/385

**Comment by thebigredgeek** [comment]
Unfortunately I never found a way to make this work.

**Comment by thebigredgeek** [comment]
Happy to review a PR to make this work.  Until then, closing the issue
