### ISSUE TITLE
Working with Apollo Server 2.0

### ISSUE THREAD

**Issue by dakshshah96** [thebigredgeek/apollo-errors#44]
How would I use `apollo-errors` with Apollo Server 2.0? Example:

```
const { ApolloServer, gql } = require('apollo-server');

// Construct a schema, using GraphQL schema language
const typeDefs = gql`
  type Query {
    announcement: String
  }
`;

// Provide resolver functions for your schema fields
const resolvers = {
  Query: {
    announcement: () =>
      `Say hello to the new Apollo Server! A production ready GraphQL server with an incredible getting started experience.`
  }
};

const server = new ApolloServer({ typeDefs, resolvers });

server.listen().then(({ url }) => {
  console.log(`🚀 Server ready at ${url}`);
});
```

**Comment by theGlenn** [comment]
Apollo 2.0 already implements a built error handling mechanism. You can check it at: https://www.apollographql.com/docs/apollo-server/v2/features/errors.html

**Comment by thebigredgeek** [comment]
Yep true but it's super basic!

**Comment by theGlenn** [comment]
@dakshshah96 @thebigredgeek , with Apollo's new system, error generation might be the way to go. A simple script that generates Apollo error classes from a JSON definition file.

**Comment by thebigredgeek** [comment]
That sounds neat! Down to explore it

**Comment by theGlenn** [comment]
I got inspired a little started working on this here project is called [apollo-pythian](https://github.com/theGlenn/apollo-pythian) not yet production ready tho.

I created an issue to make it work with third party library Apollo libraries like `apollo-erros`
https://github.com/theGlenn/apollo-pythian/issues/2
