### ISSUE TITLE
Create V2.0 Branch

### ISSUE THREAD

**Issue by theGlenn** [thebigredgeek/apollo-errors#48]
Seems like **release 2.0** has been on hold for a little while now and important updates like #35 have not been implemented yet.

@thebigredgeek  shall we create a v2 branch and start merging features like #35 ?

Not sure what the correct workflow should be for that.

**Comment by thebigredgeek** [comment]
Yeah I think that's a good idea.  I think we should try to get as many breaking changes as possible out of the way in v2, including spec compliance.

**Comment by theGlenn** [comment]
Alright done let's try and those into version-2
https://github.com/thebigredgeek/apollo-errors/tree/version-2
