### ISSUE TITLE
message as an object

### ISSUE THREAD

**Issue by gandhiamarnadh** [thebigredgeek/apollo-errors#49]
would be helpful to define errors with message objects. (that can carry more static info regarding the error like  severity)

I would like to make a PR changing the current type of message to union of string and object

please let me know your opinion

**Comment by theGlenn** [comment]
Hey @gandhiamarnadh, could give you us more details with a code sample for example?

**Comment by gandhiamarnadh** [comment]
this is my usecase, the ui can handle errors gracefully based on severity
`export const WrongCredentialsError = createError('WrongCredentialsError', {
  message: {
  content: 'The provided credentials are invalid.',
  severity: 9,
  supportSeverity: 0
  },
});
`

**Comment by theGlenn** [comment]
The consensus in the GraphQL and Apollo community is to try and stick to the spec as much as possible.
What you are proposing is too much of change regarding what the spec says about `message`:

> Every error must contain an entry with the key message with a string description of the error intended for the developer as a guide to understand and correct the error.

Take a look at it here http://facebook.github.io/graphql/draft/#sec-Errors.

You can add static informations to your errors using `createError`:

```ts
export const WrongCredentialsError = createError('FooError', {
  message: 'A foo error has occurred',
  data: {
     severity: 9,
     supportSeverity: 0
  }
});
```

Note: The data field will be renamed `extensions` in V2

**Comment by gandhiamarnadh** [comment]
thanks @theGlenn i didn't know that data field is extensible
