### ISSUE TITLE
Is there any way to set http status code from error?

### ISSUE THREAD

**Issue by SPAHI4** [thebigredgeek/apollo-errors#5]
I tried to pass `statusCode` to options (https://github.com/apollographql/graphql-server/blob/master/packages/graphql-server-koa/src/koaApollo.ts#L41) 
```
export const ForbiddenError = createError('ForbiddenError', {
	statusCode: 403,
	message: 'Forbidden',
});
```
 , but it doesn't work.

**Comment by thebigredgeek** [comment]
Try passing the status code under the data property

**Comment by SPAHI4** [comment]
@thebigredgeek it just appears in the `data` field, I want to set status in the server response

**Comment by thebigredgeek** [comment]
Hmm.  Apollo-errors doesn't interact with the HTTP response.  It doesn't set status codes either.  That is handled by whatwg-fetch if you are using the default Network Interface with apollo-client.  Can you tell me a little more about what you are doing or trying to do?  Or what issues you are having?  It sounds like it might not have anything to do with apollo-errors, but I would love to help you in any case :)
