### ISSUE TITLE
Dynamic messages

### ISSUE THREAD

**Issue by lucasconstantino** [thebigredgeek/apollo-errors#6]
Great work with this module!

There is one thing missing, though: I would like to have dynamic messages for my errors when possible. To make that happen, `message` option could be received as function.

As you don't expose ApolloError, things are harder they it should to increment your lib. Here is a work around I'm using to achieve it:

```js
const createDynamicError = (name, opts = {}) => class CustomError {
  constructor (...args) {
    const config = typeof opts === 'string' || typeof opts === 'function'
      ? { message: opts }
      : opts

    if (typeof config.message === 'function') {
      config.message = config.message(...args)
    }

    return new (createError(name, config))(...args.slice(-1))
  }
}
```

You could then use it like so:

```js
const UserNotFoundError = createCustomError('UserNotFoundError', {
  message: username => `User ${username} not found`
})

// Or, shurtcuted:
const UserNotFoundError = createCustomError('UserNotFoundError', username => `User ${username} not found`)

// And use it like that:
new UserNotFoundError('lucas')

// Or, with data as in the original createError:
new UserNotFoundError('lucas', { data: { foo: 'bar' } })
```

Hope it helps someone ;)

**Comment by thebigredgeek** [comment]
You can already override the message when you throw the error, per the docs, with whatever string you want.  Does that not handle your use case?

**Comment by lucasconstantino** [comment]
No, not really. I wouldn't like to send the message always I throw the error, but I would like the message to contain some contextual information. If anyone else finds this useful after all, I can write the pull-request. Until then, I guess I'll keep using my wrapping helper.

**Comment by thebigredgeek** [comment]
Interesting.  I think we could definitely add this to the package, but I am wondering how we ought to make the API work without breaking changes.  Any thoughts @lucasconstantino ?

**Comment by scf4** [comment]
IMO this is more of a UI detail, to be implemented in a client rather than at the API level.

**Comment by thebigredgeek** [comment]
@scf4 I mostly agree, but I also don't feel overly pained about adding this if enough people want it.  That said, there is nothing stopping anyone from using a factory function to return errors with dynamic messages without baking any new functionality into the lib.

**Comment by thebigredgeek** [comment]
I'm closing this for now, since there doesn't seem to be any interest in moving forward
