### ISSUE TITLE
createError fails with no second argument

### ISSUE THREAD

**Issue by riley-stroud-ck** [thebigredgeek/apollo-errors#9]
The optional second argument is not really optional
```
apollo-errors/dist/index.js:87
  var data = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : { message: 'An error has occurred', options: options };
                                                                                                                              ^
ReferenceError: options is not defined
```
```
var createError = exports.createError = function createError(name) {
  var data = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : { message: 'An error has occurred', options: options };

  var e = ApolloError.bind(null, name, data);
  return e;
};
```

**Comment by thebigredgeek** [comment]
`options` is not optional.  some of the fields ON `options` are optional, but a message property on the options object is required.  I think the solution here is an `assert` clause that gives a proper error message about `options` being required (per the docs, as well)

**Comment by thebigredgeek** [comment]
https://github.com/thebigredgeek/apollo-errors/blob/master/src/index.js#L44 < there is a syntax error, though, with initializing a `default` second param... `options` isn't defined.  The default should be removed and we should use `assert` to test for validity of the second parameter

**Comment by ch-andrewrhyne** [comment]
@riley-stroud-ck any interest in submitting a PR for the syntax error fix?

**Comment by thebigredgeek** [comment]
@riley-stroud-ck  any interest in submitting a PR for the syntax error fix?

**Comment by thebigredgeek** [comment]
Should be fixed [here](https://github.com/thebigredgeek/apollo-errors/releases/tag/1.5.0)
